/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package deux.sdk.reservation

import deux.reservation.sdk.Library
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
