[versions]
kotlin = "1.8.0"
junitJupiterEngineVersion = "5.9.1"

[libraries]
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinTestJunit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiterEngineVersion" }
