[versions]
#kotlin = "1.8.0"
junitJupiterEngineVersion = "5.9.1"
ktor_version = "2.3.2"
kotlin_version = "1.9.0"
logback_version = "1.2.11"

[libraries]
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin_version" }
kotlinTestJunit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
kotlinTestJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin_version" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiterEngineVersion" }
ktorServerCoreJvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor_version" }
ktorServerOpenApi = { module = "io.ktor:ktor-server-openapi", version.ref = "ktor_version" }
ktorServerNettyJvm = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor_version" }
ktorServerTestsJvm = { module = "io.ktor:ktor-server-tests-jvm", version.ref = "ktor_version" }
logbackCassic = { module = "ch.qos.logback:logback-classic", version.ref = "logback_version" }

